### ISSUE TITLE
Price movement prediction using sentiment analysis

### ISSUE THREAD

**Issue by DavidMajomi** [DavidMajomi/Stock-Market-Analysis#5]

**Comment by JesseMurah** [comment]
Any task @DavidMajomi ?

**Comment by DavidMajomi** [comment]
> Any task @DavidMajomi ?

Do you mean if I have a task or if you have a task?
If you mean me, yes I do. I just created a  basic python server client program to communicate data across, I do have some performance / memory tradeoffs to ask the group about though.
If you mean yourself, Dagi and I are still thinking about how to solve the API problem, I intend to bring it up tomorrow. But your team could go ahead and create a group chat for that, or I could create one and add you guys.

**Comment by JesseMurah** [comment]
Okay got that
